# Generated by Django 4.2.10 on 2024-04-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('IN PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('explanation', models.TextField(blank=True, default=None, null=True)),
                ('filenames', models.CharField(blank=True, default=None, max_length=2048, null=True)),
                ('attached_user', models.CharField(max_length=200)),
                ('resolved_notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
