# Generated by Django 4.2.10 on 2024-04-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_report_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
