# Generated by Django 4.2.10 on 2024-04-09 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0004_alter_report_submission_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='submission_time',
        ),
    ]
