# Generated by Django 4.2.10 on 2024-04-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0006_report_submission_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
