# Generated by Django 4.2.10 on 2024-04-14 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0003_tag_report_tags'),
        ('file_upload', '0007_alter_report_id'),
    ]

    operations = [
    ]
