# Generated by Django 4.2.10 on 2024-04-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("file_upload", "0008_merge_0003_tag_report_tags_0007_alter_report_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="location",
            field=models.TextField(blank=True, null=True),
        ),
    ]
