# Generated by Django 4.2.10 on 2024-04-24 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0009_report_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='rating',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
