# Generated by Django 4.2.11 on 2024-04-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0010_report_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
